#!/bin/bash
set +x
#
# vim:tabstop=3:expandtab:shiftwidth=3
#
###############################################################################
#
# Helper script for ssh to run batch ssh commands
# Example script:
#
#  #!/bin/bash
#
#  # This line will request your to enter your password
#  $(ssh_askpass --exports)
#
#  COMMAND='ls -l'
#  HOSTS="host1 host2 host3"
#
#  for HOST in $HOSTS
#  do
#     $SETSID ssh $HOST "$COMMAND"
#  done
#
#
# For multiple user accounts, replace the line with the next line:
#
#  $(ssh_askpass --exports hans have verha)
#
#
# -> disadvantage: You have to enter 3 passwords when running the script.
#                  By setting up the vault, only the vault secret will
#                  be requested.
#
# setup vault:
#
#  ssh_askpass --vault-create hans have verha
#
# script line with an enabled vault:
#
#  $(ssh_askpass --exports)
#
# managing the passwords in the vault:
#
#  ssh_askpass --update-passwords
#
# -> Only the changed password need to be entered, the others can be
#    skipped (old value) by pressing <Enter>
#
# For equal named accounts with different passwords 2 facilities are available.
# The account can be provided including the @<hostname-regular-expression>
#
#   or 
#
# In the ~/.ssh/askpass file arrays with regular expressions can be setup.
# Example:
#
# AIX=(
# 'aix000006'
# 'aix[1-9].*'
# )
# 
# Solaris=(
# 'sun000001'
# 'sun[1-9].*'
# )
#
# Example setup:
#
#  ssh_askpass --vault-create hv1234=AIX hv1234=Solaris hans@lin hans ""
#  
# This will request for 5 passwords + the vault secret (2x)
#
# [hv1234=AIX@ssh_askpass] Enter password:
# [hv1234=Solaris@ssh_askpass] Enter password:
# [hans@lin@ssh_askpass] Enter password:
# [hans@ssh_askpass] Enter password:
# [ssh_askpass] Enter password:
# [ssh_askpass] Lock vault secret:
# [ssh_askpass] Check vault secret:
#
# A login with hv1234@<system> will be first searched in AIX, then in
# Solaris, then with the direct regular expression hv1234@lin.* and
# finally the last unfiltered value will be returned.
#
# A login with hans will return the 4th password and an unknown will return
# the last password.
#
# Testing can be done by running:
#
#  $SSH_ASKPASS nobody@system
#  $SSH_ASKPASS hv1234@sun000001
#  $SSH_ASKPASS hv1234@aix100006
#  $SSH_ASKPASS hans@lin
#  $SSH_ASKPASS hans@pc
#
#  Author  : Hans vervaart
#  Requires: _option_processor
#
###############################################################################

# find out if this file is executed or sourced
(return 0 2>/dev/null) && sourced=1 || sourced=0

# If sourced, then $0 does not exist. ___ bypasses _option_processor
___0="${BASH_SOURCE[0]}"
___0_dirname=$(dirname $___0)
___0_basename=$(basename "$___0")

# Get the "ssh" ($___1_) and "askpass" ($___0_) part of "ssh_askpass"
___1_=$(echo "$___0_basename" | cut -d_ -f1)
___0_=$(echo "$___0_basename" | cut -d_ -f2)
___BIN=$(echo "$___0_basename" | tr '[:lower:]' '[:upper:]') # SSH_ASKPASS
___CACHE=$(echo "${___BIN}_CACHE") # SSH_ASKPASS_CACHE

# Save original mask
UMASK_=$(umask)

# Keep files private
umask 0177

# The walk-in vars
NrOfArgs=$#

# For the options processor
_help_show_args="[account] .."
[ -r $___0_dirname/_option_processor ] && . $___0_dirname/_option_processor



if [ $sourced = 0 ]
then
   # Create .ssh dir if not available
   if [ "$HOME" != "" ]
   then
      [ ! -d "$HOME/.${___1_}" ] && \
         (umask 0077 && mkdir $HOME/.${___1_}) &> /dev/null
   fi
   if [ ! -f "$HOME/.${___1_}/${___0_}" ]
   then
      touch $HOME/.${___1_}/${___0_} > /dev/null 2>&1 \
         || touch $HOME/.${___0_} > /dev/null 2>&1
      chmod 600 $HOME/.${___1_}/${___0_} > /dev/null 2>&1 \
         || chmod 600 $HOME/.${___0_} > /dev/null 2>&1
   fi
fi

# Source the arrays and create the ability to change global vars
___0D="${___1_}/${___0_}"
if [ ! -r $HOME/."$___0D" ]
then
   ___0D=${___0_}
fi

. $HOME/.${___0D} > /dev/null 2>&1

VaultFile=$HOME/.${___0D}.vault
CheckFile=$HOME/.${___0D}.check
AlgoritmFile=$HOME/.${___0D}.algorithm

OPEN_SSL=$(which openssl 2> /dev/null | grep '^/')

OPEN_SSL_ALGORITHM=""
if [ -r "$AlgoritmFile" ]
then
   OPEN_SSL_ALGORITHM=$(cat "$AlgoritmFile")
else
   # Check if we have a current openssl binary that supports -pbkdf2
   strings $OPEN_SSL |grep -q PKCS5_PBKDF2
   if [ $? = 0 ]
   then
      iters=$((90000 + RANDOM % 1000))
      OPEN_SSL_ALGORITHM="-aes-256-cbc -pbkdf2 -iter $iters"
   else
      OPEN_SSL_ALGORITHM="-aes-256-cbc"
   fi
   echo "$OPEN_SSL_ALGORITHM" > "$AlgoritmFile"  2> /dev/null
fi
SETSID=$(which setsid 2> /dev/null | grep '^/')
[ "$SETSID" = "" ] && SETSID=$(which setpgrp 2> /dev/null | grep '^/')
[ "$SETSID" = "" ] && SETSID="$___0_dirname/setsid.pl"

trap 'stty sane > /dev/null 2>&1 ; printf "^C\r\n" ; umask '"$UMASK_"' ; exit 1' HUP INT QUIT TERM

# Option processor normaly by insource, but the 'engine' copied in
# Option processor start
while echo $1 | grep '^[-][-][a-z0-9-][a-z0-9-]*$'  > /dev/null 2>&1 || \
      echo $1 | grep '^[-][a-zA-Z0-9][a-zA-Z0-9]*$' > /dev/null 2>&1
do
   if echo $1 | grep '^[-][-]' > /dev/null 2>&1
   then
      # --long-style-options
      __Opts=`echo "$1" | sed -e 's,-*$,,g' -e 's,-,_,g'`
   else
      # -s -h -ort -Style (short style options)
      __Opts=`echo "$1" | sed -e 's,^-,,' -e 's,\(.\),_\1 ,g'`
   fi
   shift
   for __Opt in $__Opts
   do
      if eval echo "\$$__Opt" | grep '^$' > /dev/null 2>&1
      then
         unset ${__Opt}_ARG
      fi
      if [ $# -gt 0 ] && \
         cat $___0 | tr '$' '\n' | sed 's/$/#/' | \
         egrep "^[{]{0,1}${__Opt}_ARG[^A-Za-z_]" > /dev/null 2>&1
      then
         eval ${__Opt}_ARG[$\{#${__Opt}_ARG[@]\}]=\"$1\"
         shift
      fi
      eval $__Opt='yes'
   done
done
unset __Opts __Opt
if [ "$_h" = "yes" ] || [ "$__help" = "yes" ]
then
   echo "Help not available" >&2
   exit 1
fi
# End option processor

if [ $NrOfArgs -eq 0 ]
then
   exec $___0 -h
fi

EchoExports()
{
   if [ "$__no_set" != "yes" ]
   then
      SET=set
   fi

   if [ "${!___CACHE}" != "" ]
   then
      for EnvVar in ${___CACHE} ${___BIN} DISPLAY DISPLAY_ SETSID
      do
         if echo $SHELL | grep '/sh$' > /dev/null 2>&1
         then
            echo "$SET $EnvVar=$(eval echo \$${EnvVar}) ; export $EnvVar"
         else
            echo "export $EnvVar=$(eval echo \$${EnvVar})"
         fi
      done
   fi
}

if [ "$__vault_create" = "yes" ]
then
   touch $VaultFile
fi

if [ "$__vault_remove" = "yes" ]
then
   rm -f $VaultFile
   exit 0
fi

if [ "$__flush_cache" = "yes" ]
then
   [ $NrOfArgs -eq 1 ] && echo
   for EnvVar in ${___CACHE} ${___BIN} SETSID
   do
      unset $EnvVar
      [ $NrOfArgs -eq 1 ] && echo " unset $EnvVar"
   done
   if [ ! -z "$DISPLAY_" ]
   then
      DISPLAY=$DISPLAY_
      unset DISPLAY_
   fi
   [ $NrOfArgs -eq 1 ] && echo
   __vault_ignore="yes"

fi

unset Passw
if [ "$OPEN_SSL" != "" ] && [ -s $VaultFile ] &&
   [ "$__vault_ignore" != "yes" ]
then
   while [ "${!___CACHE}" = "" ]
   do
      printf "[$___0_basename] Open vault secret:" >&2 ; read -r -s Passw
      printf "%.${#Passw}d\n" '0' | tr '0' '*' >&2
      export Passw
      $(cat $VaultFile 2> /dev/null | $OPEN_SSL base64 -d | \
      ($OPEN_SSL enc -pass env:Passw $OPEN_SSL_ALGORITHM -salt \
                    -in /dev/stdin -out /dev/stdout -d | \
      gunzip -c) 2> /dev/null) > /dev/null 2>&1
      if [ "${!___CACHE}" = "" ]
      then
         echo "Unable to open the vault, wait for retry" >&2
         sleep 3
      fi
   done
fi

if [ "$__vault_show" = "yes" ] && [ ! -s $VaultFile ]
then
   MSG_="Nothing to show you, there is no vault file."
   echo "echo '$MSG_'"
   exit 4
fi


# Input new account passwords
if  [ "$__flush_cache" != "yes" ]
then
if [ "${!___CACHE}" = "" ] || [ "$__vault_create" = "yes" ] || \
   [ "$__update_passwords" = "yes" ] || [ "$__vault_relock" = "yes" ] || \
   [ "$__vault_show" = "yes" ]
then
   if [ "$__vault_relock" != "yes" ] || [ "$__update_passwords" = "yes" ] || \
      [ "$__vault_show" = "yes" ]
   then
      Check='#'
      unset Accounts
      while [ $# -ne 0 ]
      do
         Accounts[${#Accounts[@]}]="$1"
         shift
      done
      if [ ${#Accounts[@]} -eq 0 ]
      then
         if [ "${!___CACHE}" != "" ]
         then
            for Acc in $(echo "${!___CACHE}" | tr '-' '\n' | \
                         $OPEN_SSL base64 -d  2> /dev/null | \
                         gunzip -c 2>/dev/null | \
                         grep -v '^#' | sed -e 's/^/"/' -e 's/:.*/"/')
            do
               eval Accounts[${#Accounts[@]}]=$Acc
            done
         fi
      fi
      NrAccounts=${#Accounts[@]}
      # No account, any account will be OK
      if [ ${#Accounts[@]} -eq 0 ]
      then
         NrAccounts=1
      fi
      while [ "$Check" != "" ]
      do
         unset Values Value
         i=0
         unset Value
         while [ $i -lt $NrAccounts ] || [ "$Value" = "" ]
         do
            printf "[%s$___0_basename] Enter password:" \
               "$(echo ${Accounts[$i]} | sed 's/.$/\0@/')" >&2
            unset UnChanged
            if [ "$__vault_show" != "yes" ]
            then
               read -r -s Value
            else
               unset Value
               __vault_ignore="yes"
            fi
            if [ "$Value" = "" ] && [ "${!___CACHE}" != "" ]
            then
               Value="$(echo "${!___CACHE}" | tr '-' '\n' | \
                        $OPEN_SSL base64 -d  2> /dev/null | \
                        gunzip -c 2>/dev/null | \
                        grep -v '^#' | grep "^${Accounts[$i]}:" | \
                        sed 's/.*://' | tr '-' '\n' | \
                        $OPEN_SSL base64 -d 2> /dev/null)"
               if [ "$Value" != "" ]
               then
                  UnChanged=' (unchanged)'
               fi
            fi
            if [ "$Value" != "" ]
            then
               Values[$i]="$(printf "%s" "$Value" | $OPEN_SSL base64)"
               i=$(($i+1))
               echo "$Value" | sed -e 's/./*/g' -e "s/\$/$UnChanged/" >&2
            else
               echo >&2
            fi
         done
         Value="$(
            (
               i=0
               echo "#${RANDOM}"
               while [ $i -lt $NrAccounts ]
               do
                  echo "${Accounts[$i]}:${Values[$i]}"
                  i=$(($i+1))
               done
             ) | gzip -c | $OPEN_SSL base64 | tr '\n' '-')"
         if [ -r $CheckFile ] && [ "$OPEN_SSL" != "" ]
         then
            Check=$(echo "$Value" | tr '-' '\n' | $OPEN_SSL base64 -d | \
                    gunzip -c | grep -v '^#' | $OPEN_SSL md5 | \
                    awk '{print $NF}')
            if [ "$(head -1 $CheckFile 2> /dev/null)" \
                 = "$Check" ]
            then
               unset Check
            else
               printf "Password(s) changed? (yes/no) " >&2
               read Changed
               if [ "$Changed" = "yes" ]
               then
                  echo "$Check" > $CheckFile
                  unset Check
               fi
            fi
         else
            unset Check
         fi
         if [ "$Check" = "" ]
         then
            declare ${___CACHE}="$Value"
            export ${___CACHE}
            declare ${___BIN}=$(cd $___0_dirname;pwd)/$___0_basename
            export ${___BIN}
            if [ -z "$DISPLAY_" ] && [ ! -z "$DISPLAY" ]
            then
               DISPLAY_=$DISPLAY
            fi
            [ "$DISPLAY" = "" ] && DISPLAY=localhost:0.0
            export DISPLAY
            export SETSID
         fi
      done
   fi

   if [ "${!___CACHE}" != "" ] && [ "$OPEN_SSL" != "" ] && \
      ( [ "$__vault_create" = "yes" ] || \
        ( [ -f $VaultFile ] && [ "$__vault_ignore" != "yes" ] ) )
   then
      if [ "$__vault_relock" = "yes" ]
      then
         unset Passw
      fi
      unset PwdCh
      while [ ${#Passw} -eq 0 ]
      do
         printf "[$___0_basename] Lock vault secret:" >&2 ; read -r -s Passw
         printf "%.${#Passw}d\n" '0' | tr '0' '*' >&2
         if [ ${#Passw} -ne 0 ]
         then
            printf "[$___0_basename] Check vault secret:" >&2 ; read -r -s PwdCh
            printf "%.${#PwdCh}d\n" '0' | tr '0' '*' >&2
            export Passw PwdCh
            if [ ${#PwdCh} -eq 0 ] || \
               ! (echo "$RANDOM" | \
                  $OPEN_SSL enc $OPEN_SSL_ALGORITHM -pass env:Passw \
                              -in /dev/stdin \
                              -out /dev/stdout -e | \
                  $OPEN_SSL enc $OPEN_SSL_ALGORITHM -pass env:PwdCh \
                              -in /dev/stdin \
                              -out /dev/stdout -d ) > /dev/null 2>&1
            then
               unset PwdCh Passw
            fi
         fi
      done
      export Passw
      EchoExports | gzip -c 2> /dev/null | \
      $OPEN_SSL enc -pass env:Passw $OPEN_SSL_ALGORITHM -salt \
                    -in /dev/stdin -out /dev/stdout -e | \
      $OPEN_SSL base64 > $VaultFile
      printf "[$___0_basename] New vault content written\n"
   fi
fi
fi


if [ "${!___CACHE}" != "" ]
then
   export ${___CACHE}
   declare ${___BIN}=$(cd $___0_dirname;pwd)/$___0_basename
   export ${___BIN}
   if [ -z "$DISPLAY_" ] && [ ! -z "$DISPLAY" ]
   then
      DISPLAY_=$DISPLAY
      export DISPLAY_
   fi
   [ "$DISPLAY" = "" ] && DISPLAY=localhost:0.0
   export DISPLAY
   export SETSID

   if [ "$__exports" = "yes" ]
   then
      echo
      EchoExports | sed 's/^/ /'
      echo
   fi

   # sometimes when using a jumphost, the -o StrictHostKeyChecking=no is not propagated
   if [ $NrOfArgs -eq $# ] && [ "$1" != "" ]
   then
      echo "$1"|grep -q -e "Please type 'yes' or 'no'" -e 'Are you sure you want to continue connecting'
      if [ $? = 0 ]
      then
         echo "yes"
         NrOfArgs=0
      fi
   fi   
   
   if [ $NrOfArgs -eq $# ] && [ "$1" != "" ]
   then
      echo "${!___CACHE}" |  tr '-' '\n' | $OPEN_SSL base64 -d | \
      gunzip -c | grep -v '^#' | \
      while read Line
      do
         Arr=$(echo $Line | sed 's/:.*//' | grep -v '@' | grep '=' | \
               sed 's/.*=//')
         Acc=$(echo $Line | sed -e 's/:.*//' -e 's/=.*//')
         Pwc=$(echo $Line | sed 's/.*://')
         if [ "$Arr" != "" ] && [ $(eval echo \${#$Arr[@]}) -gt 0 ]
         then
            i=0
            while [ $i -lt $(eval echo \${#$Arr[@]}) ]
            do
               Reg="^${Acc}@$(eval echo \${$Arr[$i]})"
               if echo "$1" | grep "$Reg" > /dev/null 2>&1
               then
                  Pwd=$(echo "$Pwc" | $OPEN_SSL base64 -d)
                  echo $* "<$___0_basename> ($Arr:$Reg)" >&2
                  echo "$Pwd"
                  exit 1
               fi
               i=$(($i+1))
            done
         elif echo "$Acc" | grep '@' > /dev/null 2>&1 && \
              echo "$1" | grep "^$Acc" > /dev/null 2>&1
         then
            Pwd=$(echo "$Pwc" | $OPEN_SSL base64 -d)
            echo $* "<$___0_basename> (^$Acc)" >&2
            echo "$Pwd"
            exit 2
         elif echo "$1@" | grep "^$Acc@" > /dev/null 2>&1
         then
            Pwd=$(echo "$Pwc" | $OPEN_SSL base64 -d)
            echo $* "<$___0_basename> ($Acc)" >&2
            echo "$Pwd"
            exit 3
         fi
      done
      if [ $? -eq 0 ]
      then
         Pwd="$(echo "${!___CACHE}" | tr '-' '\n' | \
                $OPEN_SSL base64 -d | gunzip -c | \
                grep -v '^#' | grep "^:" | \
                sed 's/.*://' | $OPEN_SSL base64 -d)"
         if [ ${#Pwd} -eq 0 ]
         then
            echo $* "<$___0_basename FAILED (unknown account)>" >&2
            exit 1
         fi
         echo $* "<$___0_basename>" >&2
         echo "$Pwd"
      fi
   fi
fi

# When __flush_cache (closing the vault), allow ^C again without the terminal closing
if [ "$__no_trap" = "yes" ]
then
   trap - HUP INT QUIT TERM
fi


# Forget parameters 
unset __vault_create __vault_remove __update_passwords __vault_relock 
unset __flush_cache  __vault_ignore __exports __no_trap __no_set _h __help

# restore umask
umask "$UMASK_"
unset UMASK_
